server:
  port: 9001
  servlet:
    context-path: /sys
spring:
  datasource:
    url: jdbc:mysql://localhost:5006/kthirty
    username: root
    password: ${KTHIRTY_PASSWORD}
  data:
    redis:
      host: redis.kthirty.top
      port: 5008
      password: ${KTHIRTY_PASSWORD}

  liquibase:
    clear-checksums: true
