server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://nas.kthirty.top:5006/kthirty
    username: root
    password: ${db-password}
  liquibase:
    clear-checksums: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
