server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://mysql.kthirty.top:7091/test2024
    username: test2024
    password: ${KTHIRTY_PASSWORD}
    hikari:
      max-lifetime: 18000000000
  data:
    redis:
      host: redis.kthirty.top
      port: 5008
      password: ${KTHIRTY_PASSWORD}
#springdoc:
#  group-configs:
#    - packages-to-scan: top.kthirty.develop
#      group: 'develop'
#      paths-to-match: /**
#    - packages-to-scan: top.kthirty.system
#      group: 'system'
#      paths-to-match: /**
