spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/kthirty
    username: kthirty
    password: kthirty
mybatis-flex:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl