package top.kthirty.extra.report.config.provider;

import com.bstek.ureport.provider.report.ReportFile;
import com.bstek.ureport.provider.report.ReportProvider;
import org.springframework.beans.factory.InitializingBean;
import org.springframework.beans.factory.annotation.Autowired;

import javax.sql.DataSource;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/**
 * UReport自定义存储：优先存数据库（自动识别MySQL/Oracle并建表），无DataSource则存文件
 * @author KThirty
 */
public class DbReportProvider implements ReportProvider, InitializingBean {
    @Autowired(required = false)
    private DataSource dataSource;
    private String dbType = "";
    private final String TABLE_NAME = "ureport_file";

    @Override
    public void afterPropertiesSet() throws Exception {
        try (Connection conn = dataSource.getConnection()) {
            dbType = conn.getMetaData().getDatabaseProductName().toLowerCase();
            String createTableSql = getCreateTableSql(dbType);
            try (Statement stmt = conn.createStatement()) {
                stmt.execute(createTableSql);
            }
        }
    }

    private String getCreateTableSql(String dbType) {
        if (dbType.contains("oracle")) {
            return "CREATE TABLE ureport_file (" +
                    "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "name VARCHAR2(255) UNIQUE NOT NULL, " +
                    "content CLOB NOT NULL, " +
                    "update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP" +
                    ")";
        } else { // 默认MySQL
            return "CREATE TABLE IF NOT EXISTS ureport_file (" +
                    "id BIGINT PRIMARY KEY AUTO_INCREMENT, " +
                    "name VARCHAR(255) UNIQUE NOT NULL, " +
                    "content TEXT NOT NULL, " +
                    "update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP" +
                    ")";
        }
    }

    @Override
    public InputStream loadReport(String file) {
        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement("SELECT content FROM " + TABLE_NAME + " WHERE name=?")) {
            ps.setString(1, file);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                String content = rs.getString("content");
                return new ByteArrayInputStream(content.getBytes(StandardCharsets.UTF_8));
            }
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
        return null;
    }

    @Override
    public void saveReport(String file, String content) {
        try (Connection conn = dataSource.getConnection()) {
            PreparedStatement ps = conn.prepareStatement("SELECT id FROM " + TABLE_NAME + " WHERE name=?");
            ps.setString(1, file);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                PreparedStatement update = conn.prepareStatement("UPDATE " + TABLE_NAME + " SET content=?, update_time=? WHERE name=?");
                update.setString(1, content);
                update.setTimestamp(2, new Timestamp(System.currentTimeMillis()));
                update.setString(3, file);
                update.executeUpdate();
            } else {
                PreparedStatement insert = conn.prepareStatement("INSERT INTO " + TABLE_NAME + " (name, content, update_time) VALUES (?, ?, ?)");
                insert.setString(1, file);
                insert.setString(2, content);
                insert.setTimestamp(3, new Timestamp(System.currentTimeMillis()));
                insert.executeUpdate();
            }
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    public void deleteReport(String file) {
        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement("DELETE FROM " + TABLE_NAME + " WHERE name=?")) {
            ps.setString(1, file);
            ps.executeUpdate();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    public List<ReportFile> getReportFiles() {
        List<ReportFile> files = new ArrayList<>();
        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement("SELECT name, update_time FROM " + TABLE_NAME);
             ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                String name = rs.getString("name");
                Timestamp updateTime = rs.getTimestamp("update_time");
                files.add(new ReportFile(name, updateTime));
            }
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
        return files;
    }

    @Override
    public String getPrefix() {
        return "db";
    }

    @Override
    public String getName() {
        return "数据库文件存储";
    }

    @Override
    public boolean disabled() {
        return false;
    }
}
