server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://mysql.kthirty.top:7091/test2024
    username: test2024
    password: ${KTHIRTY_PASSWORD}
  data:
    redis:
      host: localhost

  liquibase:
    show-summary: off


#ureport:
#  disableHttpSessionReportCache: false
#  disableFileProvider: false
#  fileStoreDir: /ureportfiles
#  debug: true

