server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://8.141.4.177:34/kthirty?autoReconnect=true&useUnicode=true&characterEncoding=utf8&nullCatalogMeansCurrent=true
    username: root
    password: ${KTHIRTY_PASSWORD}
  data:
    redis:
      host: localhost

  liquibase:
    show-summary: off


