server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://localhost:5006/kthirty
    username: root
    password: ${KTHIRTY_PASSWORD}
  data:
    redis:
      host: localhost

  liquibase:
    show-summary: off


